"""initial schema: users, tenders, tender_analyses, company_profiles, notifications

Revision ID: da60cbaf67b1
Revises: 
Create Date: 2026-09-23 13:34:32.767691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da60cbaf67b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('core_services', sa.JSON(), nullable=False),
    sa.Column('target_geographies', sa.JSON(), nullable=False),
    sa.Column('minimum_score_threshold', sa.Float(), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_id'), 'company_profiles', ['id'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('buyer', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('deadline_str', sa.String(length=100), nullable=True),
    sa.Column('raw_summary', sa.Text(), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_external_id'), 'tenders', ['external_id'], unique=True)
    op.create_index(op.f('ix_tenders_id'), 'tenders', ['id'], unique=False)
    op.create_index(op.f('ix_tenders_source'), 'tenders', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_tender_id'), 'notifications', ['tender_id'], unique=False)
    op.create_table('tender_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('is_fit', sa.Boolean(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('matched_services', sa.JSON(), nullable=False),
    sa.Column('eligibility_gaps', sa.JSON(), nullable=False),
    sa.Column('suggested_next_steps', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'UNDER_REVIEW', 'BIDDING', 'DISCARDED', name='tenderstatus'), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id')
    )
    op.create_index(op.f('ix_tender_analyses_id'), 'tender_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_analyses_id'), table_name='tender_analyses')
    op.drop_table('tender_analyses')
    op.drop_index(op.f('ix_notifications_tender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenders_source'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_external_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_company_profiles_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
